### PR TITLE
Fixes guoger/stupid/#43

### PR DESCRIPTION
**Pull request by SamYuan1990**
Signed-off-by: SamYuan1990 <yy19902439@126.com>

### CODE REVIEW

**Comment by SamYuan1990** [comment]
https://dev.azure.com/guojiannan1101/guojiannan1101/_build/results?buildId=210&view=logs&j=4b84b62c-66d5-5fa0-c35b-f166f90ef4e2&t=014dcebe-97a7-582a-ee19-3d3efff13357

test log.

**Comment by guoger** [comment]
a proper commit message should look like:
```
Summary of what the code does

Detailed descriptions of what problem this commit solves
and what approach it takes. Ideally, we also explain what
test has been added to prove its functionalities.

fix #xx
```

note that `fix #xx` is just a handy way to automatically close issue. **we still need all the descriptions, since that's preserved in our commit history**

**Comment by guoger** [comment]
I think we should hold off merging this:
- it's not clear to me how useful this is **for now**
- it complicates code
- there _might_ be performance regression

**Comment by guoger** [comment]
@SamYuan1990  let's close this PR, and we could always revisit in the future

**Pull request closed without merging**
